linters:
  BorderZero:
    enabled: true

  ColorKeyword:
    enabled: true

  Intendation:
    enabled: true
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  NestingDepth:
    enabled: true
    max_depth: 6

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 6